version: '3'

networks:
  laravel:

services:
  nginx:
    image: nginx:1.20.2-alpine
    container_name: nginx
    ports:
      - "9080:80"
    volumes:
      - ./api:/var/www
      - ./nginx/api/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: docker
      MYSQL_USER: newuser
      MYSQL_PASSWORD: passwor434
      MYSQL_ROOT_PASSWORD: passwor434
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./api:/var/www
    ports:
      - "9000:9000"
    networks:
      - laravel